# Generated by Django 5.0.4 on 2024-04-04 17:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myTelegramUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToyCoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='TOY COIN', max_length=20)),
                ('quantity_mined', models.DecimalField(decimal_places=2, default='100.00', max_digits=10)),
                ('time_clicked', models.DateTimeField()),
                ('first_click', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('mineral_extracted', models.CharField(blank=True, max_length=50, null=True)),
                ('extraction_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_coin', to='myTelegramUser.telegramuser')),
            ],
        ),
    ]
