# Generated by Django 5.0.4 on 2024-04-05 10:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toycoin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toycoin',
            name='extraction_date',
        ),
        migrations.AddField(
            model_name='toycoin',
            name='launch_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
