# Generated by Django 5.0.4 on 2024-04-09 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myTelegramUser', '0002_telegramuser_full_name_telegramuser_language_code_and_more'),
        ('toycoin', '0002_remove_toycoin_extraction_date_toycoin_launch_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toycoin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_coin', to='myTelegramUser.telegramuser'),
        ),
    ]
