# Generated by Django 5.0.4 on 2024-04-13 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myTelegramUser', '0002_telegramuser_full_name_telegramuser_language_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='referrer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_users', to='myTelegramUser.telegramuser'),
        ),
    ]
