# Generated by Django 5.0.4 on 2024-04-13 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myTelegramUser', '0002_telegramuser_full_name_telegramuser_language_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(default='The Users Task', max_length=1050)),
                ('time_clicked', models.DateTimeField()),
                ('completed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_task', to='myTelegramUser.telegramuser')),
            ],
        ),
    ]
