# Generated by Django 5.0.4 on 2024-04-13 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myTelegramUser', '0002_telegramuser_full_name_telegramuser_language_code_and_more'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time_clicked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='user_task', to='myTelegramUser.telegramuser'),
        ),
    ]
