# Generated by Django 5.0.4 on 2024-04-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_task_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='task',
            name='time_clicked',
        ),
        migrations.AddField(
            model_name='task',
            name='quantity',
            field=models.IntegerField(default=250),
        ),
        migrations.AddField(
            model_name='task',
            name='url',
            field=models.URLField(default='https://t.me/toyonton', max_length=1050),
            preserve_default=False,
        ),
    ]
