# Generated by Django 5.0.4 on 2024-04-22 08:47

import task.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_task_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='url',
            field=models.URLField(max_length=1050, validators=[task.models.validate_twitter_url]),
        ),
    ]
