# Generated by Django 5.0.4 on 2024-05-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_task_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='group_id',
            field=models.CharField(default='0000000000', max_length=255),
        ),
    ]
