# Generated by Django 5.0.4 on 2024-05-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_alter_task_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='group_id',
            field=models.CharField(max_length=255),
        ),
    ]
