# Generated by Django 5.0.4 on 2024-06-29 21:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myTelegramUser', '0004_telegramuser_last_active'),
        ('task', '0010_alter_task_group_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.DurationField()),
                ('user', models.ManyToManyField(blank=True, null=True, related_name='user_bot', to='myTelegramUser.telegramuser')),
            ],
        ),
    ]
