# Generated by Django 5.0.4 on 2024-06-29 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myTelegramUser', '0004_telegramuser_last_active'),
        ('task', '0011_autobot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autobot',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='autobot',
            name='user',
        ),
        migrations.AddField(
            model_name='autobot',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_bot', to='myTelegramUser.telegramuser'),
        ),
    ]
